language: ruby

sudo: false

cache: bundler

notifications:
  email:
    - piktur.io+ci@gmail.com

rvm:
  - 2.2.2
  - 2.5.1

addons:
  postgresql:
    - 9.4
    - 11.1

gemfile:
  - gemfiles/Gemfile[ruby-2.2.x][rails-4.0.x][pg-9.4.x]
  - gemfiles/Gemfile[ruby-2.5.x][rails-5.2.x][pg-11.1.x]

env:
  - DATABASE_URL=postgres://postgres@localhost/pg_multisearch_test
  - RUBY_VERSION=2.2.2
  - RUBY_VERSION=2.5.1
  - POSTGRESQL_VERSION=9.4.15
  - POSTGRESQL_VERSION=11.1.0
  - ACTIVE_RECORD_VERSION=4.0.3
  - ACTIVE_RECORD_VERSION=5.2.1

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile[ruby-2.2.x][rails-4.0.x][pg-9.4.x]
      rvm: 2.5.1
    - gemfile: gemfiles/Gemfile[ruby-2.5.x][rails-5.2.x][pg-11.1.x]
      rvm: 2.2.2

before_script:
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
  - psql -c 'CREATE DATABASE pg_multisearch_test;' -U postgres

install:
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec
